# Generated by Django 4.1.2 on 2022-11-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
    ]
