# Generated by Django 4.1.2 on 2022-12-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='random_id',
            field=models.IntegerField(default=1105338),
        ),
    ]
