# Generated by Django 4.1.1 on 2022-11-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('session_id', 'product')},
        ),
    ]
