# Generated by Django 4.1.2 on 2022-12-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marketplace", "0002_remove_address_address_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="random_id",
            field=models.IntegerField(default=7641677),
        ),
    ]
