# Generated by Django 4.1.2 on 2022-11-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marketplace", "0002_product_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(default=5),
        ),
    ]
